In [2]:
import numpy as np
import pandas as pd
import requests

In [13]:
def requisicao(pais):
    request = requests.get(f'http://universities.hipolabs.com/search?country={pais}')
    requisicao = request.json()
    df = pd.DataFrame(requisicao)
    return df

In [14]:
def dataframe():
    df2 = pd.concat([requisicao("Brazil"), requisicao("Portugal")], join="outer")
    return df2

In [15]:
dataframe()

,domains,name,web_pages,country,state-province,alpha_two_code
0,[baraodemaua.br],Centro Universitário Barao de Maua,[http://www.baraodemaua.br/],Brazil,None,BR
1,[brazcubas.br],Universidade Braz Cubas,[http://www.brazcubas.br/],Brazil,None,BR
2,[candidomendes.br],Universidade Candido Mendes,[http://www.candidomendes.br/],Brazil,None,BR
3,[castelobranco.br],Universidade Castelo Branco,[http://www.castelobranco.br/],Brazil,None,BR
4,[claretiano.edu.br],Centro Universitário Claretiano,[http://www.claretiano.edu.br/],Brazil,None,BR
...,...,...,...,...,...,...
121,[uportu.pt],Universidade Portucalense Infante D. Henrique,[http://www.uportu.pt/],Portugal,None,PT
122,[up.pt],Universidade do Porto,[http://www.up.pt/],Portugal,None,PT
123,[utad.pt],Universidade de Tras-os-Montes e Alto Douro,[http://www.utad.pt/],Portugal,None,PT
124,[utl.pt],Universidade Tecnica de Lisboa,[http://www.utl.pt/],Portugal,None,PT
125,[novasbe.unl.pt],Nova School of Business and Economics,[https://www.novasbe.unl.pt/en/],Portugal,None,PT